name: Proof HTML
on:
  push:
  workflow_dispatch:
    inputs:
      cloud-name:
        description: Cloud name
        type: choice
        required: true
        default: AWS
        options: 
          - AWS
          - GCP
          - AZURE
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./
